name: TryHackMe Update Badge
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  tryhackme-badge-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate Badge
        uses: p4p1/tryhackme-badge-workflow@main
        with:
          username: 'JatinKhanduri'
      - name: Deploy Badge
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add tryhackme.svg || true
          git commit -m "Update TryHackMe badge" || exit 0
          git push